# 第 11 章 期约与异步函数

## 异步编程

:::code 同步与异步

ECMAScript 6 新增了正式的 Promise（期约）引用类型，支持优雅地定义和组织异步逻辑。
ECMAScript 6 使用 async 和 await 关键字定义异步函数的机制。

同步行为和异步行为的对立统一是计算机科学的一个基本概念。
特别是在 JavaScript 这种单线程事件循环模型中，同步操作与异步操作更是代码所要依赖的核心机制。
异步行为是为了优化因计算量大而时间长的操作。
如果在等待其他操作完成的同时，即使运行其他指令，系统也能保持稳定，那么这样做就是务实的。
同步行为对应内存中顺序执行的处理器指令。每条指令都会严格按照它们出现的顺序来执行，而每条指令执行后也能立即获得存储在系统本地的信息。

```js
let x = 3;
console.log("setTimeout前x的值：" + x);
setTimeout(() => {
  x = x + 4;
  console.log("setTimeout中x的值：" + x);
}, 1000);
console.log("setTimeout后x的值：" + x);
//setTimeout前x的值：3
//setTimeout后x的值：3
//setTimeout中x的值：7
```

:::

:::code 以往的异步编程模式

```js
let x = 3;
console.log("setTimeout前x的值：" + x);
setTimeout(() => {
  x = x + 4;
  console.log("setTimeout中x的值：" + x);
}, 1000);
console.log("setTimeout后x的值：" + x);
//setTimeout前x的值：3
//setTimeout后x的值：3
//setTimeout中x的值：7
```

:::

## 期约

:::code 期约基础

ECMAScript 6 新增的引用类型 Promise（期约异步编程机制），可以通过 new 操作符来实例化。
创建新期约时需要传入执行器（executor）函数作为参数。

期约是一个有状态的对象，可能处于如下 3 种状态之一：

- 待定（pending）
- 兑现（fulfilled，有时候也称为“解决”，resolved）
- 拒绝（rejected）

待定（pending）是期约的最初始状态。
在待定状态下，期约可以落定（settled）为代表成功的兑现（fulfilled）状态，或者代表失败的拒绝（rejected）状态。
无论落定为哪种状态都是不可逆的。只要从待定转换为兑现或拒绝，期约的状态就不再改变。

执行器函数主要有两项职责：初始化期约的异步行为和控制状态的最终转换。
控制期约状态的转换是通过调用它的两个函数参数实现的。两个函数参数: resolve()和 reject()。
调用resolve()会把状态切换为兑现，调用 reject()会把状态切换为拒绝。调用 reject()也会抛出错误。

```js
let p = new Promise(() => {});
console.log(p); //Promise {<pending>}
let p1 = new Promise((resolve, reject) => resolve());
console.log(p1); // Promise <resolved>
let p2 = new Promise((resolve, reject) => reject());
console.log(p2); // Promise <rejected>
// Uncaught error (in promise)

//执行器函数是同步执行的。这是因为执行器函数是期约的初始化程序。
new Promise(() => setTimeout(console.log, 0, "executor"));
setTimeout(console.log, 0, "promise initialized");
// executor
// promise initialized

//添加 setTimeout 可以推迟切换状态：
let p3 = new Promise((resolve, reject) => setTimeout(resolve, 1000));
// 在 console.log 打印期约实例的时候，还不会执行超时回调（即 resolve()）
setTimeout(console.log, 0, p3); // Promise <pending>

//无论 resolve()和 reject()中的哪个被调用，状态转换都不可撤销了。于是继续修改状态会静默失败，如下所示：
let p4 = new Promise((resolve, reject) => {
  resolve();
  reject(); // 没有效果
});
setTimeout(console.log, 0, p4); // Promise <resolved>

// 为避免期约卡在待定状态，可以添加一个定时退出功能。
let p5 = new Promise((resolve, reject) => {
  setTimeout(reject, 5000); // 10 秒后调用 reject()
  // 执行函数的逻辑
});
setTimeout(console.log, 0, p5); // Promise <pending>
setTimeout(console.log, 6000, p5); // 11 秒后再检查状态
// (After 5 seconds) Uncaught error
// (After 6 seconds) Promise <rejected>

//通过调用Promise.resolve()静态方法，可以实例化一个解决的期约。
let p6 = new Promise((resolve, reject) => resolve());
let p7 = Promise.resolve();
setTimeout(console.log, 0, Promise.resolve()); // Promise <resolved>: undefined
setTimeout(console.log, 0, Promise.resolve(3)); // Promise <resolved>: 3
// 多余的参数会忽略
setTimeout(console.log, 0, Promise.resolve(4, 5, 6)); // Promise <resolved>: 4
//Promise.resolve()可以说是一个幂等方法，
let p8 = Promise.resolve(7);
setTimeout(console.log, 0, p8 === Promise.resolve(p8));
// true
setTimeout(console.log, 0, p8 === Promise.resolve(Promise.resolve(p8)));
// true

//与 Promise.resolve()类似，Promise.reject()会实例化一个拒绝的期约并抛出一个异步错误（这个错误不能通过 try/catch 捕获，而只能通过拒绝处理程序捕获）。
//两个期约实例实际上是一样的
let p9 = new Promise((resolve, reject) => reject());
let p10 = Promise.reject();
let p11 = Promise.reject(3);
setTimeout(console.log, 0, p11); // Promise <rejected>: 3
p11.then(null, e => setTimeout(console.log, 0, e)); // 3

//Promise.reject()并没有照搬 Promise.resolve()的幂等逻辑。如果给它传一个期约对象，则这个期约会成为它返回的拒绝期约的理由：
setTimeout(console.log, 0, Promise.reject(Promise.resolve())); // Promise <rejected>: Promise <resolved>

//第一个 try/catch 抛出并捕获了错误，第二个 try/catch 抛出错误却没有捕获到。
try {
  throw new Error("foo");
} catch (e) {
  console.log(e); // Error: foo
}
try {
  Promise.reject(new Error("bar"));
} catch (e) {
  console.log(e);
}
// Uncaught (in promise) Error: bar
```

:::

:::code 期约的实例方法
期约实例的方法是连接外部同步代码与内部异步代码之间的桥梁。
这些方法可以访问异步操作返回的数据，处理期约成功和失败的结果，连续对期约求值，或者添加只有期约进入终止状态时才会执行的代码。

1. 实现 Thenable 接口。Promise 类型实现了 Thenable 接口。
2. Promise.prototype.then() 两个参数：onResolved 处理程序和 onRejected 处理程序。
3. Promise.prototype.catch()方法用于给期约添加拒绝处理程序。相当于调用 Promise.prototype.then(null, onRejected)。
4. Promise.prototype.finally()方法用于给期约添加 onFinally 处理程序，这个处理程序在期约转换为解决或拒绝状态时都会执行。
5. 非重入期约方法。当期约进入落定状态时，与该状态相关的处理程序仅仅会被排期，而非立即执行。
6. 邻近处理程序的执行顺序。如果给期约添加了多个处理程序，当期约状态变化时，相关处理程序会按照添加它们的顺序依次执行。
7. 传递解决值和拒绝理由。期约会提供其解决值（如果兑现）或其拒绝理由（如果拒绝）给相关状态的处理程序。
8. 拒绝期约与拒绝错误处理。拒绝期约类似于 throw()表达式，因为它们都代表一种程序状态，即需要中断或者特殊处理。

:::

:::code Promise.prototype.then()

```js
function onResolved(id) {
  setTimeout(console.log, 0, id, "resolved");
}
function onRejected(id) {
  setTimeout(console.log, 0, id, "rejected");
}
let promise1 = new Promise((resolve, reject) => setTimeout(resolve, 3000));
let promise2 = new Promise((resolve, reject) => setTimeout(reject, 3000));
promise1.then(() => onResolved("promise1"), () => onRejected("promise1"));
promise2.then(() => onResolved("promise2"), () => onRejected("promise2"));
//（3 秒后）
// promise1 resolved
// promise2 rejected

let p1 = Promise.reject("foo");
// 调用 then()时不传处理程序则原样向后传
let p2 = p1.then();
// Uncaught (in promise) foo
// 这些都一样
let p3 = p1.then(null, () => undefined);
let p4 = p1.then(null, () => {});
let p5 = p1.then(null, () => Promise.resolve());
setTimeout(console.log, 0, p3); // Promise <resolved>: undefined
setTimeout(console.log, 0, p4); // Promise <resolved>: undefined
setTimeout(console.log, 0, p5); // Promise <resolved>: undefined
// 这些都一样
let p6 = p1.then(null, () => "bar");
let p7 = p1.then(null, () => Promise.resolve("bar"));
setTimeout(console.log, 0, p6); // Promise <resolved>: bar
setTimeout(console.log, 0, p7); // Promise <resolved>: bar
// Promise.resolve()保留返回的期约
let p8 = p1.then(null, () => new Promise(() => {}));
let p9 = p1.then(null, () => Promise.reject());
// Uncaught (in promise): undefined
setTimeout(console.log, 0, p8); // Promise <pending>
setTimeout(console.log, 0, p9); // Promise <rejected>: undefined
let p10 = p1.then(null, () => {
  throw "baz";
});
// Uncaught (in promise) baz
setTimeout(console.log, 0, p10); // Promise <rejected>: baz
let p11 = p1.then(null, () => Error("qux"));
setTimeout(console.log, 0, p11); // Promise <resolved>: Error: qux
```

:::

:::code Promise.prototype.then()

```js
let p = Promise.reject();
let onRejected = function(e) {
  setTimeout(console.log, 0, "rejected");
};
// 这两种添加拒绝处理程序的方式是一样的：
p.then(null, onRejected); // rejected
p.catch(onRejected); // rejected
let p1 = new Promise(() => {});
let p2 = p1.catch();
setTimeout(console.log, 0, p1); // Promise <pending>
setTimeout(console.log, 0, p2); // Promise <pending>
setTimeout(console.log, 0, p1 === p2); // false
```

:::

:::code Promise.prototype.finally()

```js
let p1 = Promise.resolve();
let p2 = Promise.reject();
let onFinally = function() {
  setTimeout(console.log, 0, "Finally!");
};
p1.finally(onFinally); // Finally
p2.finally(onFinally); // Finally
//Promise.prototype.finally()方法返回一个新的期约实例：
let p3 = new Promise(() => {});
let p4 = p3.finally();
setTimeout(console.log, 0, p3); // Promise <pending>
setTimeout(console.log, 0, p4); // Promise <pending>
setTimeout(console.log, 0, p3 === p4); // false

let p11 = Promise.resolve("foo");
// 这里都会原样后传
let p21 = p11.finally();
let p31 = p11.finally(() => undefined);
let p41 = p11.finally(() => {});
let p51 = p11.finally(() => Promise.resolve());
let p61 = p11.finally(() => "bar");
let p71 = p11.finally(() => Promise.resolve("bar"));
let p81 = p11.finally(() => Error("qux"));
setTimeout(console.log, 0, p21); // Promise <resolved>: foo
setTimeout(console.log, 0, p31); // Promise <resolved>: foo
setTimeout(console.log, 0, p41); // Promise <resolved>: foo
setTimeout(console.log, 0, p51); // Promise <resolved>: foo
setTimeout(console.log, 0, p61); // Promise <resolved>: foo
setTimeout(console.log, 0, p71); // Promise <resolved>: foo
setTimeout(console.log, 0, p81); // Promise <resolved>: foo
```

:::

:::code 非重入期约方法

```js
let synchronousResolve;
// 创建一个期约并将解决函数保存在一个局部变量中
let p = new Promise(resolve => {
  synchronousResolve = function() {
    console.log("1: invoking resolve()");
    resolve();
    console.log("2: resolve() returns");
  };
});
p.then(() => console.log("4: then() handler executes"));
synchronousResolve();
console.log("3: synchronousResolve() returns");
// 实际的输出：
// 1: invoking resolve()
// 2: resolve() returns
// 3: synchronousResolve() returns
// 4: then() handler executes

let p1 = Promise.resolve();
p1.then(() => console.log("p1.then() onResolved"));
console.log("p1.then() returns");
let p2 = Promise.reject();
p2.then(null, () => console.log("p2.then() onRejected"));
console.log("p2.then() returns");
let p3 = Promise.reject();
p3.catch(() => console.log("p3.catch() onRejected"));
console.log("p3.catch() returns");
let p4 = Promise.resolve();
p4.finally(() => console.log("p4.finally() onFinally"));
console.log("p4.finally() returns");
// p1.then() returns
// p2.then() returns
// p3.catch() returns
// p4.finally() returns
// p1.then() onResolved
// p2.then() onRejected
// p3.catch() onRejected
// p4.finally() onFinally
```

:::

:::code 邻近处理程序的执行顺序

```js
let p1 = Promise.resolve();
let p2 = Promise.reject();
p1.then(() => setTimeout(console.log, 0, 1));
p1.then(() => setTimeout(console.log, 0, 2));
// 1
// 2
p2.then(null, () => setTimeout(console.log, 0, 3));
p2.then(null, () => setTimeout(console.log, 0, 4));
// 3
// 4
p2.catch(() => setTimeout(console.log, 0, 5));
p2.catch(() => setTimeout(console.log, 0, 6));
// 5
// 6
p1.finally(() => setTimeout(console.log, 0, 7));
p1.finally(() => setTimeout(console.log, 0, 8));
// 7
// 8
```

:::

:::code 传递解决值和拒绝理由

```js
let p1 = new Promise((resolve, reject) => resolve("foo"));
p1.then(value => console.log(value)); // foo
let p2 = new Promise((resolve, reject) => reject("bar"));
p2.catch(reason => console.log(reason)); // bar

let p3 = Promise.resolve("foo");
p3.then(value => console.log(value)); // foo
let p4 = Promise.reject("bar");
p4.catch(reason => console.log(reason)); // bar
```

:::

:::code 期约连锁与期约合成

```js
let p1 = new Promise((resolve, reject) => reject(Error("foo")));
let p2 = new Promise((resolve, reject) => {
  throw Error("foo");
});
let p3 = Promise.resolve().then(() => {
  throw Error("foo");
});
let p4 = Promise.reject(Error("foo"));
setTimeout(console.log, 0, p1); // Promise <rejected>: Error: foo
setTimeout(console.log, 0, p2); // Promise <rejected>: Error: foo
setTimeout(console.log, 0, p3); // Promise <rejected>: Error: foo
setTimeout(console.log, 0, p4); // Promise <rejected>: Error: foo
//Uncaught (in promise) Error: foo 
//Uncaught (in promise) Error: foo 
//Uncaught (in promise) Error: foo 
//Uncaught (in promise) Error: foo 

new Promise((resolve, reject) => {
  console.log("begin asynchronous execution");
  reject(Error("bar"));
})
  .catch(e => {
    console.log("caught error", e);
  })
  .then(() => {
    console.log("continue asynchronous execution");
  });
// begin asynchronous execution
// caught error Error: bar
// continue asynchronous execution
```

:::

:::code 期约连锁与期约合成

Promise.all()静态方法创建的期约会在一组期约全部解决之后再解决。这个静态方法接收一个可迭代对象，返回一个新期约
Promise.race()静态方法返回一个包装期约，是一组集合中最先解决或拒绝的期约的镜像。这个方法接收一个可迭代对象，返回一个新期约

```js
```

:::

:::code Promise.all()

```js
//合成的期约只会在每个包含的期约都解决之后才解决：
let p = Promise.all([
  Promise.resolve(),
  new Promise((resolve, reject) => setTimeout(resolve, 1000))
]);
setTimeout(console.log, 0, p); // Promise <pending>
p.then(() => setTimeout(console.log, 0, "all() resolved!"));
// all() resolved!（大约 1 秒后）

//如果至少有一个包含的期约待定，则合成的期约也会待定。如果有一个包含的期约拒绝，则合成的期约也会拒绝：
// 永远待定
let p1 = Promise.all([new Promise(() => {})]);
setTimeout(console.log, 0, p1); // Promise <pending>
// 一次拒绝会导致最终期约拒绝
let p2 = Promise.all([Promise.resolve(), Promise.reject(), Promise.resolve()]);
setTimeout(console.log, 0, p2); // Promise <rejected>
// Uncaught (in promise) undefined

//如果所有期约都成功解决，则合成期约的解决值就是所有包含期约解决值的数组，按照迭代器顺序：
let p3 = Promise.all([
  Promise.resolve(3),
  Promise.resolve(),
  Promise.resolve(4)
]);
p3.then(values => setTimeout(console.log, 0, values)); // [3, undefined, 4]

// 虽然只有第一个期约的拒绝理由会进入
// 拒绝处理程序，第二个期约的拒绝也
// 会被静默处理，不会有错误跑掉
let p4 = Promise.all([
  Promise.reject(3),
  new Promise((resolve, reject) => setTimeout(reject, 1000))
]);
p4.catch(reason => setTimeout(console.log, 0, reason)); // 3

```

:::

:::code Promise.race()

```js
let p1 = Promise.race([Promise.resolve(), Promise.resolve()]);
// 可迭代对象中的元素会通过 Promise.resolve()转换为期约
let p2 = Promise.race([3, 4]);
// 空的可迭代对象等价于 new Promise(() => {})
let p3 = Promise.race([]);
// 无效的语法
//let p4 = Promise.race();
// TypeError: cannot read Symbol.iterator of undefined

// 解决先发生，超时后的拒绝被忽略
let p11 = Promise.race([
  Promise.resolve(3),
  new Promise((resolve, reject) => setTimeout(reject, 1000))
]);
setTimeout(console.log, 0, p11); // Promise <resolved>: 3
// 拒绝先发生，超时后的解决被忽略
let p21 = Promise.race([
  Promise.reject(4),
  new Promise((resolve, reject) => setTimeout(resolve, 1000))
]);
setTimeout(console.log, 0, p21); // Promise <rejected>: 4
// 迭代顺序决定了落定顺序
let p31 = Promise.race([
  Promise.resolve(5),
  Promise.resolve(6),
  Promise.resolve(7)
]);
setTimeout(console.log, 0, p31); // Promise <resolved>: 5
// 虽然只有第一个期约的拒绝理由会进入
// 拒绝处理程序，第二个期约的拒绝也
// 会被静默处理，不会有错误跑掉
let p = Promise.race([
  Promise.reject(3),
  new Promise((resolve, reject) => setTimeout(reject, 1000))
]);
p.catch(reason => setTimeout(console.log, 0, reason)); // 3
```

:::

:::code 串行期约合成

```js
//这种模式可以提炼出一个通用函数，可以把任意多个函数作为处理程序合成一个连续传值的期约连锁。这个通用的合成函数可以这样实现：
function addTwo(x) {
  return x + 2;
}
function addThree(x) {
  return x + 3;
}
function addFive(x) {
  return x + 5;
}
function compose(...fns) {
  return x => fns.reduce((promise, fn) => promise.then(fn), Promise.resolve(x));
}
let addTen = compose(
  addTwo,
  addThree,
  addFive
);
addTen(8).then(console.log); // 18
```

:::

## 异步函数

:::code 异步函数
ES8 的 async/await 旨在解决利用异步结构组织代码的问题。为此，ECMAScript 对函数进行了扩展，为其增加了两个新关键字：async 和 await。
async 关键字用于声明异步函数。这个关键字可以用在函数声明、函数表达式、箭头函数和方法上
await 关键字必须在异步函数中使用，不能在顶级上下文如`<script>`标签或模块中使用。await必须和async一起使用。在同步函数内部使用 await 会抛出 SyntaxError。

```js
async function foo() {
  console.log(1);
  return 3;
}
// 给返回的期约添加一个解决处理程序
foo().then(console.log);
console.log(2);
// 1
// 2
// 3
// 返回一个期约
async function qux() {
  return Promise.resolve("qux");
}
qux().then(console.log);
// qux

//在期约处理程序中一样，在异步函数中抛出错误会返回拒绝的期约：
async function foo1() {
  console.log(1);
  throw 3;
}
// 给返回的期约添加一个拒绝处理程序
foo1().catch(console.log);
console.log(2);
// 1
// 2
// 3

//拒绝期约的错误不会被异步函数捕获：
async function foo2() {
  console.log(1);
  Promise.reject(3);
}
// Attach a rejected handler to the returned promise
foo2().catch(console.log);
console.log(2);
// 1
// 2
// Uncaught (in promise): 3


// 等待一个原始值
async function foo11() {
  console.log(await "foo");
}
foo11();
// foo
// 等待一个没有实现 thenable 接口的对象
async function bar11() {
  console.log(await ["bar"]);
}
bar11();
// ['bar']
// 等待一个实现了 thenable 接口的非期约对象
async function baz11() {
  const thenable = {
    then(callback) {
      callback("baz");
    }
  };
  console.log(await thenable);
}
baz11();
// baz
// 等待一个期约
async function qux11() {
  console.log(await Promise.resolve("qux"));
}
qux11();
// qux
```

:::

:::code 停止和恢复执行

控制台中输出结果的顺序很好地解释了运行时的工作过程：
(1) 打印 1；
(2) 调用异步函数 foo()；
(3)（在 foo()中）打印 2；
(4)（在 foo()中）await 关键字暂停执行，向消息队列中添加一个期约在落定之后执行的任务；
(5) 期约立即落定，把给 await 提供值的任务添加到消息队列；
(6) foo()退出；
(7) 打印 3；
(8) 调用异步函数 bar()；
(9)（在 bar()中）打印 4；
(10)（在 bar()中）await 关键字暂停执行，为立即可用的值 6 向消息队列中添加一个任务；
(11) bar()退出；
(12) 打印 5；
(13) 顶级线程执行完毕；
(14) JavaScript 运行时向消息队列中添加一个恢复执行 foo()函数的任务；
(15) JavaScript 运行时从消息队列中取出解决 await 期约的处理程序，并将解决的值 6 提供给它；
(16) 异步任务完成，JavaScript 从消息队列中取出恢复执行 foo()的任务及值 6；
(17)（在 foo()中）打印 6；
(18)（在 foo()中）打印 9；
(19) foo()返回。
(20) JavaScript 运行时从消息队列中取出恢复执行 bar()的任务及值 6；
(21)（在 bar()中）恢复执行，await 取得值 6；
(22)（在 bar()中）打印 8；
(23)（在 bar()中）打印 9；
(24) bar()返回；

```js
async function foo() {
  console.log(2);
  console.log(await Promise.resolve(6));
  console.log(7);
}
async function bar() {
  console.log(4);
  console.log(await 8);
  console.log(9);
}
console.log(1);
foo();
console.log(3);
bar();
console.log(5);
//1
//2
//3
//4
//5
//6
//7
//8
//9
```

:::

:::code 异步函数策略 实现 sleep()

```js
async function sleep(delay) { 
 return new Promise((resolve) => setTimeout(resolve, delay)); 
} 
async function fooSleep() { 
 const t0 = Date.now(); 
 await sleep(1500); // 暂停约 1500 毫秒
 console.log(Date.now() - t0); 
} 
fooSleep(); 
// 1502
```

:::

:::code 异步函数策略 利用平行执行

```js
//如果顺序不是必需保证的，那么可以先一次性初始化所有期约，然后再分别等待它们的结果。
async function sleep(delay) { 
 return new Promise((resolve) => setTimeout(resolve, delay)); 
} 
async function fooSleep() { 
 const t0 = Date.now(); 
 await sleep(1500); // 暂停约 1500 毫秒
 console.log(Date.now() - t0); 
} 
fooSleep(); 
// 1502

async function randomDelay(id) {
  // 延迟 0~1000 毫秒
  const delay = Math.random() * 1000;
  return new Promise(resolve =>
    setTimeout(() => {
      console.log(`${id} finished`);
      resolve(id);
    }, delay)
  );
}
async function foo() {
  const t0 = Date.now();
  const promises = Array(5)
    .fill(null)
    .map((_, i) => randomDelay(i));
  for (const p of promises) {
    console.log(`awaited ${await p}`);
  }
  console.log(`${Date.now() - t0}ms elapsed`);
}
foo();
// 1 finished
// 2 finished
// 4 finished
// 3 finished
// 0 finished
// awaited 0
// awaited 1
// awaited 2
// awaited 3
// awaited 4
// 645ms elapsed

```

:::

:::code 异步函数策略 串行执行期约

```js
async function addTwo(x) {
  return x + 2;
}
async function addThree(x) {
  return x + 3;
}
async function addFive(x) {
  return x + 5;
}
async function addTen(x) {
  for (const fn of [addTwo, addThree, addFive]) {
    x = await fn(x);
  }
  return x;
}
addTen(9).then(console.log); // 19
```

:::

:::code 异步函数策略 栈追踪与内存管理

```js
function fooPromiseExecutor(resolve, reject) { 
 setTimeout(reject, 1000, 'bar'); 
} 
async function foo() { 
 await new Promise(fooPromiseExecutor); 
} 
foo(); 
// Uncaught (in promise) bar 
// foo
// async function (async) 
// foo
```

:::
